//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NailSalon.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int IdOrderService { get; set; }
        public int IdOrder { get; set; }
        public int IdService { get; set; }
        public int IdEmployee { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Service Service { get; set; }
    }
}
